### ISSUE TITLE
Ability to use Distance tool on map for already entered georeference coordinates.

### ISSUE THREAD

**Issue by MiguelGrande** [themerekat/CCH2-wish-list#18]
It would be useful to add the Distance tool to the map for already georeferenced coordinates, in order to add distance data to the label information.  For example, distances from landmarks or along roads could be entered from visualizing and measuring on the map. Alternatively, if the GeoLocate tool automatically went to entered coordinates as a first choice, that would work, but it does not do that currently.

**Comment by CCH2-portal** [comment]
The georeferenced point does show up in GeoLocate, you just need to select it from the list of points. There currently is no measurement tool in the Google Maps pop up, regardless of whether the specimen has already been georeferenced. GeoLocate is your best bet.
