### ISSUE TITLE
Checklists: Desire ability to sort by higher level taxonomic groups

### ISSUE THREAD

**Issue by MiguelGrande** [themerekat/CCH2-wish-list#19]
Most plant checklists sort by higher level groups, usually bryophytes first, then lycophytes, then ferns (in the broad sense), gymnosperms, and angiosperms.  In the latter, sorting by dicots (preferably "basal" angiosperms and eudicots) and monocots is often done.  Those higher level categories are already present in the data.  Request that the Checklists be capable of sorting that way.

**Comment by themerekat** [comment]
Transferred to SSH feature request list

**Comment by themerekat** [comment]
https://github.com/BioKIC/symbiota-docs/issues/207
