### ISSUE TITLE
Eliminate mapping of old, wrong determinations

### ISSUE THREAD

**Issue by MiguelGrande** [themerekat/CCH2-wish-list#27]
There seems to be a problem with mapping CCH2 records that I see. A map search will pull all records that list a particular name, even if the name was from an old determination that was corrected. So, a given map can show several records that were corrected to other taxa. 

I understand the desire not to remove past determinations in a search, but I don't think it's a good idea in mapping. The point of having experts annotate specimens is to correct the identity, not to allow it to persist.  I think there are two ways to solve this: 1) Change the code to map only those taxa listed as the current determination; 2) Add a box to check that gives this as either the default or as an option. 

If there is a symbol to force this type of exact mapping, please let us know. Put a little note on the main search page.

**Comment by themerekat** [comment]
![image](https://user-images.githubusercontent.com/16688784/110369304-702c2600-8007-11eb-8ce1-9f28ecf2ce4a.png)

**Comment by themerekat** [comment]
This was a bug with CHSC specimens. Fixed
